#note that file paths are relative to the pipeline directory
root: "/fast/work/groups/ag_ohler/dharnet_m/senescence_ribo/"
REF_orig: "/fast/work/groups/ag_ohler/dharnet_m/genomes/hg38.fa"
GTF_orig: "../ext_data/annotation/gencode.v30.annotation.gtf"
GFF_orig: "../ext_data/annotation/gencode.v30.annotation.gff3"
collapse_reads_script: "../src/pipeline_scripts/collapse_reads.pl"
REMOVE8NBIN: "../src/pipeline_scripts/remove8N_twoarg.pl"
MINREADLENGTH: 18
MAXREADLENGTH: 100
QUALLIM: 20
sample_files: "../src/read_files.csv"
sample_parameter: "../src/sample_parameter.csv"
multiqcscript: '../src/multiqc'
rnaseqpipescriptdir: 'src/pipeline_scripts/'
STARTCODTRIM: 15
STOPCODTRIM: 5